package com.mehdi.taskflow.project;

import java.util.List;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Data access for {@link Project} entities.
 *
 * <p>The method bodies are generated by Spring Data from the method names: {@code findByOwnerId}
 * becomes a query on the owner foreign key. Renaming a method therefore changes the query it runs,
 * and renaming an entity field breaks every method naming it, at application startup rather than at
 * compile time.
 */
@Repository
public interface ProjectRepository extends JpaRepository<Project, Long> {

    /**
     * Returns every project owned by a user.
     *
     * @param ownerId the identifier of the owning user
     * @return the owned projects, an empty list if none
     */
    List<Project> findByOwnerId(Long ownerId);

    /**
     * Checks in a single query whether a project exists and belongs to a given user.
     *
     * <p>Used as the ownership guard before a mutation. Combining both conditions here rather than
     * loading the project and comparing its owner in Java keeps the decision in one round trip, and
     * leaves no window between the read and the check.
     *
     * @param id the project identifier
     * @param ownerId the identifier of the user expected to own it
     * @return {@code true} if the project exists and is owned by that user
     */
    boolean existsByIdAndOwnerId(Long id, Long ownerId);
}
