package com.mehdi.taskflow.user;

import java.util.Optional;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Data access for {@link User} entities.
 *
 * <p>The method bodies are generated by Spring Data from the method names: {@code findByUsername}
 * becomes a query on the {@code username} column. Renaming a method therefore changes the query it
 * runs, and renaming an entity field breaks every method naming it, at application startup rather
 * than at compile time.
 */
@Repository
public interface UserRepository extends JpaRepository<User, Long> {

    /**
     * Finds a user by username. Used by the authentication flow, where the identifier may be either
     * a username or an email address.
     *
     * @param username the exact username to look up, case-sensitive
     * @return the matching user, or an empty {@link Optional} if none exists
     */
    Optional<User> findByUsername(String username);

    /**
     * Finds a user by email address.
     *
     * @param email the exact email address to look up, case-sensitive
     * @return the matching user, or an empty {@link Optional} if none exists
     */
    Optional<User> findByEmail(String email);

    /**
     * Checks whether a username is already taken. Preferred over {@code
     * findByUsername().isPresent()} when the entity itself is not needed: the query selects a count
     * rather than hydrating a row.
     *
     * @param username the exact username to test, case-sensitive
     * @return {@code true} if an account already holds this username
     */
    boolean existsByUsername(String username);

    /**
     * Checks whether an email address is already registered.
     *
     * @param email the exact email address to test, case-sensitive
     * @return {@code true} if an account already holds this address
     */
    boolean existsByEmail(String email);
}
